export const AUTH_START= 'AUTH_START';
export const AUTH_SUCCESS= 'AUTH_SUCCESS';
export const AUTH_FAIL= 'AUTH_FAIL';
export const AUTH_LOGOUT= 'AUTH_LOGOUT';

export const SET_REDERECT_PATH= 'SET_REDERECT_PATH';

// export const FETCH_PERSONS_START= 'FETCH_PERSONS_START';
// export const FETCH_PERSONS_SUCCESS= 'FETCH_PERSONS_SUCCESS';
// export const FETCH_PERSONS_FAIL= 'FETCH_PERSONS_FAIL';


